Repository gravwell/wiki, pull requests merged in 2022-08, with the labels that each got.

#447 add filetype documentation
  search/complete-module-list.md
  search/filetype/filetype.md
  search/filetype/filetype.png
  search/processingmodules.md
Labels: documentation

#448 add some more explanation and the supported filters
  search/filetype/filetype.md
Labels: documentation, enhancement

#459 adding some screenshots about additional PDF controls, covers issue #451
  flows/nodes/pdf-example5.png
  flows/nodes/pdf-example6.png
  flows/nodes/pdf.md
Labels: documentation, enhancement

#460 Adding additional language around limits and the "other" bucket
  search/chart/chart.md
  search/chart/chart_other1.png
  search/chart/chart_other2.png
Labels: documentation, enhancement

#461 additional docs around accelerators and query modules
  search/extractionmodules.md
Labels: documentation, enhancement

#462 documenting max resource size info
  configuration/parameters.md
  search/search.md
  search/table/table.md
Labels: documentation, enhancement

#465 fixing logos and issue 64
  distributed/OverwatchMutiple.png
  distributed/overwatch.png
Labels: enhancement, task

#468 adding updated training link
  quickstart/quickstart.md
Labels: task
